# Generated by Django 4.1.2 on 2022-10-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titile',
            new_name='title',
        ),
    ]
